version: '3.8'

services:
  waagen-kalibrierung:
    build: .
    ports:
      - "4173:4173"
    environment:
      NODE_ENV: production  # Setze dies auf 'production', wenn du in der Produktion bist.
